# Generated by Django 4.1 on 2022-08-23 17:51

from django.db import migrations, models
import network.all.base_model.validators.base_validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='name',
            field=models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 64 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Object with this name already exists.'}, help_text='Object name.', max_length=64, unique=True, validators=[network.all.base_model.validators.base_validators.NameValueValidator()], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 64 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Object with this name already exists.'}, help_text='Object name.', max_length=64, unique=True, validators=[network.all.base_model.validators.base_validators.NameValueValidator()], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 64 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Object with this name already exists.'}, help_text='Object name.', max_length=64, unique=True, validators=[network.all.base_model.validators.base_validators.NameValueValidator()], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 64 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Object with this name already exists.'}, help_text='Object name.', max_length=64, unique=True, validators=[network.all.base_model.validators.base_validators.NameValueValidator()], verbose_name='Name'),
        ),
    ]
