# Generated by Django 4.1 on 2022-08-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_credential_name_alter_device_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-pk'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterField(
            model_name='device',
            name='credential',
            field=models.ForeignKey(blank=True, help_text='Credential needed to establish SSH / HTTPS connection.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.credential', verbose_name='Credential'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, help_text='Type of network device system.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory.devicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='devicetypetemplate',
            name='device_type',
            field=models.ForeignKey(help_text='Type of network device system.', on_delete=django.db.models.deletion.PROTECT, related_name='device_type_templates', to='inventory.devicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='group',
            name='root_folder',
            field=models.ForeignKey(blank=True, help_text='The parent folder to witch the current folder belongs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_folders', to='inventory.group', verbose_name='Root folder'),
        ),
    ]
