# Generated by Django 4.1 on 2022-08-23 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time of the change creation.', verbose_name='Timestamp')),
                ('app_name', models.CharField(help_text='Name of the object application.', max_length=64, verbose_name='Object application name')),
                ('model_name', models.CharField(help_text='Name of the object model.', max_length=64, verbose_name='Object model name')),
                ('object_id', models.IntegerField(blank=True, help_text='Correlated object ID representation.', null=True, verbose_name='Object ID')),
                ('object_representation', models.CharField(blank=True, help_text='Object representation.', max_length=256, null=True, verbose_name='Object representation')),
                ('action', models.IntegerField(choices=[(0, '---'), (1, 'Create'), (2, 'Update'), (3, 'Delete')], default=0, help_text='The action that was performed on a given model.', verbose_name='Change log action')),
                ('source', models.IntegerField(choices=[(0, '---'), (1, 'GUI'), (2, 'API'), (3, 'Code')], default=0, help_text='Source of action.', verbose_name='Source of action')),
                ('after', models.JSONField(blank=True, help_text='JSON object representation after changes was made, and saved to database.', null=True, verbose_name='JSON object representation')),
                ('administrator', models.ForeignKey(blank=True, help_text='Administrator responsible for change.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
            ],
            options={
                'verbose_name': 'Change log',
                'verbose_name_plural': 'Change logs',
                'ordering': ['-pk'],
            },
        ),
    ]
