# Generated by Django 4.1 on 2022-08-14 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time of the change creation.', verbose_name='Timestamp')),
                ('object_id', models.IntegerField(help_text='Correlated object ID representation.', verbose_name='Object ID')),
                ('action', models.IntegerField(choices=[(0, '---'), (1, 'Create'), (2, 'Update'), (3, 'Delete')], default=0, help_text='The action that was performed on a given model.', verbose_name='Change log action')),
                ('after', models.JSONField(blank=True, help_text='JSON object representation after changes was made, and saved to database.', null=True, verbose_name='JSON object representation')),
                ('administrator', models.ForeignKey(blank=True, help_text='Administrator responsible for change.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
                ('content_type', models.ForeignKey(help_text='Administrator responsible for change.', on_delete=django.db.models.deletion.PROTECT, to='content.contenttype', verbose_name='Content type')),
            ],
            options={
                'verbose_name': 'Change log',
                'verbose_name_plural': 'Change logs',
            },
        ),
    ]
