# Generated by Django 4.1 on 2022-08-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='source',
        ),
    ]
