# Generated by Django 4.0.7 on 2022-08-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='object_id',
            field=models.IntegerField(blank=True, help_text='Correlated object ID representation.', null=True, verbose_name='Object ID'),
        ),
    ]
