# Generated by Django 4.0.7 on 2022-08-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0003_changelog_object_representation'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='source',
            field=models.IntegerField(choices=[(0, '---'), (1, 'GUI'), (2, 'API'), (3, 'Code')], default=0, help_text='The action that was performed on a given model.', verbose_name='Change log action'),
        ),
    ]
