# Generated by Django 4.0.7 on 2022-08-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0004_changelog_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='source',
            field=models.IntegerField(choices=[(0, '---'), (1, 'GUI'), (2, 'API'), (3, 'Code')], default=0, help_text='Source of action.', verbose_name='Source of action'),
        ),
    ]
