# Generated by Django 4.1 on 2022-08-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_value', models.BooleanField(default=False, help_text='Test model with root option cannot be deleted.', verbose_name='Root')),
                ('active', models.BooleanField(default=True, help_text='Status of test model object.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'TestModel',
                'verbose_name_plural': 'TestModels',
            },
        ),
    ]
