# Generated by Django 4.1 on 2022-08-03 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='active',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, help_text='Status of test model object.', verbose_name='Active'),
            preserve_default=False,
        ),
    ]
