# Generated by Django 4.1 on 2022-08-03 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_remove_testmodel_active_testmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Your ame.', max_length=32, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='description',
            field=models.TextField(help_text='Status of test model object.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='test_value',
            field=models.BooleanField(default=False, help_text='Test model with root option cannot be deleted.', verbose_name='Test value'),
        ),
    ]
