# Generated by Django 4.1 on 2022-08-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='color',
            field=models.IntegerField(default=1, help_text='Color object mark.', verbose_name='Object color'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='root',
            field=models.BooleanField(default=False, help_text='Root object cannot be deleted.', verbose_name='Root'),
        ),
        migrations.AlterField(
            model_name='device',
            name='color',
            field=models.IntegerField(default=1, help_text='Color object mark.', verbose_name='Object color'),
        ),
        migrations.AlterField(
            model_name='device',
            name='root',
            field=models.BooleanField(default=False, help_text='Root object cannot be deleted.', verbose_name='Root'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='color',
            field=models.IntegerField(default=1, help_text='Color object mark.', verbose_name='Object color'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='root',
            field=models.BooleanField(default=False, help_text='Root object cannot be deleted.', verbose_name='Root'),
        ),
        migrations.AlterField(
            model_name='devicetypetemplate',
            name='color',
            field=models.IntegerField(default=1, help_text='Color object mark.', verbose_name='Object color'),
        ),
        migrations.AlterField(
            model_name='devicetypetemplate',
            name='root',
            field=models.BooleanField(default=False, help_text='Root object cannot be deleted.', verbose_name='Root'),
        ),
        migrations.AlterField(
            model_name='group',
            name='color',
            field=models.IntegerField(default=1, help_text='Color object mark.', verbose_name='Object color'),
        ),
        migrations.AlterField(
            model_name='group',
            name='root',
            field=models.BooleanField(default=False, help_text='Root object cannot be deleted.', verbose_name='Root'),
        ),
    ]
