# Generated by Django 4.1 on 2022-08-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_credential_color_alter_credential_root_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetypetemplate',
            name='special',
            field=models.BooleanField(default=False, help_text='Spacial type of Device type template object.', verbose_name='Special template'),
        ),
    ]
