# Generated by Django 4.1 on 2022-08-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_devicetypetemplate_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetypetemplate',
            name='vrf',
            field=models.BooleanField(default=False, help_text='VRF cli command template.', verbose_name='VRF cli'),
        ),
    ]
