# Generated by Django 4.1 on 2022-08-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_devicetypetemplate_vrf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetypetemplate',
            name='command',
            field=models.CharField(blank=True, help_text='CLI command that will be executed on network device.', max_length=64, null=True, verbose_name='CLI command'),
        ),
        migrations.AlterField(
            model_name='devicetypetemplate',
            name='vrf',
            field=models.BooleanField(default=False, help_text='VRF cli command template.', verbose_name='VRF template'),
        ),
    ]
