# Generated by Django 4.1 on 2022-08-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_devicetypetemplate_command_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='devicetypetemplate',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='devicetypetemplate',
            name='color',
        ),
        migrations.RemoveField(
            model_name='devicetypetemplate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='devicetypetemplate',
            name='ico',
        ),
        migrations.RemoveField(
            model_name='devicetypetemplate',
            name='name',
        ),
    ]
