# Generated by Django 4.1 on 2022-08-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_devicetypetemplate_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='devices',
            field=models.ManyToManyField(help_text='All devices that belongs to current folder.', to='inventory.device', verbose_name='Devices'),
        ),
    ]
