# Generated by Django 4.1 on 2022-08-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_credential_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='device',
            managers=[
            ],
        ),
    ]
