# Generated by Django 4.0.7 on 2022-08-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetypetemplate',
            name='command',
            field=models.CharField(default='wdaw', help_text='CLI command that will be executed on network device.', max_length=64, verbose_name='CLI command'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicetypetemplate',
            name='sfm_expression',
            field=models.TextField(default='wdwa', help_text='SFM expression used to check if CLI command/s output is correct.', verbose_name='SFM expression'),
            preserve_default=False,
        ),
    ]
