# Generated by Django 4.0.7 on 2022-08-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='color',
        ),
        migrations.RemoveField(
            model_name='device',
            name='color',
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='group',
            name='color',
        ),
    ]
