# Generated by Django 4.0.7 on 2022-08-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_devicetypetemplate_command_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='devices',
            field=models.ManyToManyField(blank=True, help_text='All devices that belongs to current folder.', null=True, to='devices.device', verbose_name='Devices'),
        ),
    ]
