# Generated by Django 4.0.7 on 2022-08-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_credential_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='credential',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='devicetype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='group',
            managers=[
            ],
        ),
    ]
