# Generated by Django 4.0.7 on 2022-08-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_group_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='devices',
            field=models.ManyToManyField(help_text='All devices that belongs to current folder.', to='devices.device', verbose_name='Devices'),
        ),
    ]
