# Generated by Django 4.0.7 on 2022-08-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('devices', '0005_alter_group_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Related tags.', null=True, to='tags.tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='device',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Related tags.', null=True, to='tags.tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Related tags.', null=True, to='tags.tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='group',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Related tags.', null=True, to='tags.tag', verbose_name='Tag'),
        ),
    ]
