# Generated by Django 4.0.7 on 2022-08-17 14:31

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['name'],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='administrator',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Is super administrator.', verbose_name='Super administrator'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Administrator last login date.', null=True, verbose_name='Last login'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Profile.', related_name='user_set', related_query_name='user', to='administration.profile', verbose_name='Profile'),
        ),
    ]
