# Generated by Django 4.0.7 on 2022-08-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_administrator_groups_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='user_permissions',
        ),
    ]
