# Generated by Django 4.1 on 2022-09-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='code_id',
            field=models.CharField(blank=True, help_text='ID indicating the location of the log call in the code.', max_length=32, null=True, verbose_name='Code ID'),
        ),
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.CharField(help_text='Log message.', max_length=512, verbose_name='Message'),
        ),
    ]
