# Generated by Django 4.1 on 2022-09-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_alter_log_code_id_alter_log_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='app_name',
            field=models.CharField(blank=True, help_text='Name of the object application.', max_length=64, null=True, verbose_name='Object application name'),
        ),
        migrations.AlterField(
            model_name='log',
            name='model_name',
            field=models.CharField(blank=True, help_text='Name of the object model.', max_length=64, null=True, verbose_name='Object model name'),
        ),
    ]
