# Generated by Django 4.1 on 2022-09-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_alter_log_app_name_alter_log_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.CharField(help_text='Log message.', max_length=2048, verbose_name='Message'),
        ),
    ]
