# Generated by Django 4.1 on 2022-10-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='correlated',
            field=models.BooleanField(default=False, help_text='Correlated with all collected data models.', verbose_name='Correlated'),
        ),
    ]
