# Generated by Django 4.1 on 2022-08-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time of the change creation.', verbose_name='Timestamp')),
                ('object_id', models.IntegerField(blank=True, help_text='Correlated object ID representation.', null=True, verbose_name='Object ID')),
                ('type', models.IntegerField(choices=[(1, 'CRITICAL'), (2, 'ERROR'), (3, 'WARNING'), (4, 'INFO'), (5, 'DEBUG')], help_text='Type of notification message.', verbose_name='Notification type')),
                ('message', models.CharField(help_text='Notification message.', max_length=128, verbose_name='Message')),
                ('content_type', models.ForeignKey(blank=True, help_text='Administrator responsible for change.', null=True, on_delete=django.db.models.deletion.PROTECT, to='content.contenttype', verbose_name='Content type')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
