# Generated by Django 4.1 on 2022-08-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time of the change creation.', verbose_name='Timestamp')),
                ('app_name', models.CharField(help_text='Name of the object application.', max_length=64, verbose_name='Object application name')),
                ('model_name', models.CharField(help_text='Name of the object model.', max_length=64, verbose_name='Object model name')),
                ('object_id', models.IntegerField(blank=True, help_text='Correlated object ID representation.', null=True, verbose_name='Object ID')),
                ('type', models.IntegerField(choices=[(1, 'CRITICAL'), (2, 'ERROR'), (3, 'WARNING'), (4, 'INFO'), (5, 'DEBUG')], help_text='Type of notification message.', verbose_name='Notification type')),
                ('message', models.CharField(help_text='Notification message.', max_length=128, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-pk'],
            },
        ),
    ]
