# Generated by Django 4.1 on 2022-09-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='app_name',
            field=models.CharField(blank=True, help_text='Name of the object application.', max_length=64, null=True, verbose_name='Object application name'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='model_name',
            field=models.CharField(blank=True, help_text='Name of the object model.', max_length=64, null=True, verbose_name='Object model name'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Critical'), (2, 'Error'), (3, 'Warning'), (4, 'Info'), (5, 'Debug')], default=4, help_text='Type of notification message.', verbose_name='Notification type'),
        ),
    ]
