# Generated by Django 4.1 on 2022-10-06 15:49

from django.db import migrations, models
import network.all.base_model.validators.base_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='object last update date.', verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False, help_text='Is object deleted.', verbose_name='Deleted')),
                ('root', models.BooleanField(default=False, help_text='Root object cannot be deleted.', verbose_name='Root')),
                ('active', models.BooleanField(default=True, help_text='Object status.', verbose_name='Active')),
                ('name', models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 32 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Object with this name already exists.'}, help_text='Object name.', max_length=32, unique=True, validators=[network.all.base_model.validators.base_validators.NameValueValidator()], verbose_name='Name')),
                ('description', models.CharField(blank=True, default='Object default description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, help_text='Object description.', max_length=256, null=True, validators=[network.all.base_model.validators.base_validators.DescriptionValueValidator()], verbose_name='Description')),
                ('color', models.CharField(choices=[('aa1409', 'Dark Red'), ('f44336', 'Red'), ('e91e63', 'Pink'), ('ffe4e1', 'Rose'), ('ff66ff', 'Fuchsia'), ('9c27b0', 'Purple'), ('673ab7', 'Dark Purple'), ('3f51b5', 'Indigo'), ('2196f3', 'Blue'), ('03a9f4', 'Light Blue'), ('00bcd4', 'Cyan'), ('009688', 'Teal'), ('00ffff', 'Aqua'), ('2f6a31', 'Dark Green'), ('4caf50', 'Green'), ('8bc34a', 'Light Green'), ('cddc39', 'Lime'), ('ffeb3b', 'Yellow'), ('ffc107', 'Amber'), ('ff9800', 'Orange'), ('ff5722', 'Dark Orange'), ('795548', 'Brown'), ('c0c0c0', 'Light Grey'), ('9e9e9e', 'Grey'), ('607d8b', 'Dark Grey'), ('111111', 'Black'), ('ffffff', 'White')], default='2196f3', help_text='Tag related color.', max_length=6, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['pk'],
            },
        ),
    ]
