# Generated by Django 4.1 on 2022-10-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import system.settings.validators.base_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 64 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Settings profile with this name already exists.'}, help_text='Settings profile name.', max_length=64, unique=True, validators=[system.settings.validators.base_validators.NameValueValidator()], verbose_name='Name')),
                ('description', models.CharField(blank=True, default='Object default description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, help_text='Settings profile description.', max_length=256, null=True, validators=[system.settings.validators.base_validators.DescriptionValueValidator()], verbose_name='Description')),
                ('current', models.BooleanField(default=False, help_text='Current main application settings.', verbose_name='Current')),
                ('default_username', models.CharField(blank=True, default='cisco', help_text='Default username used by AutoCli for SSH connections.', max_length=64, null=True, verbose_name='Default username')),
                ('default_password', models.CharField(blank=True, default='!Cisco@123', help_text='Default password used by AutoCli for SSH connections.', max_length=64, null=True, verbose_name='Default password')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_username', models.CharField(blank=True, default='cisco', help_text='Default username used by AutoCli for SSH connections.', max_length=64, null=True, verbose_name='Default username')),
                ('default_password', models.CharField(blank=True, default='!Cisco@123', help_text='Default password used by AutoCli for SSH connections.', max_length=64, null=True, verbose_name='Default password')),
                ('administrator', models.ForeignKey(help_text='Settings related administrator account.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
            ],
            options={
                'verbose_name': 'User setting',
                'verbose_name_plural': 'User settings',
                'ordering': ['pk'],
            },
        ),
    ]
