# Generated by Django 4.1 on 2022-08-23 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_username', models.CharField(help_text='Default username used by AutoCli for SSH connections.', max_length=64, verbose_name='Default username')),
                ('default_password', models.CharField(blank=True, help_text='Default password used by AutoCli for SSH connections.', max_length=64, null=True, verbose_name='Default password')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_username', models.CharField(default='cisco', help_text='Default username used by AutoCli for SSH connections.', max_length=64, verbose_name='Default username')),
                ('default_password', models.CharField(default='!Cisco@123', help_text='Default password used by AutoCli for SSH connections.', max_length=64, verbose_name='Default password')),
                ('administrator', models.ForeignKey(help_text='Settings related administrator account.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
            ],
            options={
                'verbose_name': 'User setting',
                'verbose_name_plural': 'User settings',
                'ordering': ['pk'],
            },
        ),
    ]
