# Generated by Django 4.1 on 2022-08-30 17:41

from django.db import migrations, models
import system.settings.validators.base_validators


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='description',
            field=models.CharField(blank=True, default='Object default description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, help_text='Settings profile description.', max_length=256, null=True, validators=[system.settings.validators.base_validators.DescriptionValueValidator()], verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='setting',
            name='name',
            field=models.CharField(default='dwadaw', error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 64 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Settings profile with this name already exists.'}, help_text='Settings profile name.', max_length=64, unique=True, validators=[system.settings.validators.base_validators.NameValueValidator()], verbose_name='Name'),
            preserve_default=False,
        ),
    ]
