# Generated by Django 4.0.7 on 2022-08-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='default_password',
            field=models.CharField(default='!Cisco@123', help_text='Default password used by AutoCli for SSH connections.', max_length=64, verbose_name='Default password'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='default_username',
            field=models.CharField(default='cisco', help_text='Default username used by AutoCli for SSH connections.', max_length=64, verbose_name='Default username'),
        ),
    ]
