# Generated by Django 4.0.7 on 2022-08-17 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0002_alter_usersetting_default_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='administrator',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='administrator',
            field=models.ForeignKey(default=1, help_text='Settings related administrator account.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrator'),
            preserve_default=False,
        ),
    ]
