# Generated by Django 4.1 on 2022-08-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_setting_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='current',
            field=models.BooleanField(default=False, help_text='Current main application settings.', verbose_name='Current'),
        ),
    ]
