# Generated by Django 4.1 on 2022-08-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_setting_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='default_password',
            field=models.CharField(blank=True, default='!Cisco@123', help_text='Default password used by AutoCli for SSH connections.', max_length=64, null=True, verbose_name='Default password'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='default_username',
            field=models.CharField(blank=True, default='cisco', help_text='Default username used by AutoCli for SSH connections.', max_length=64, null=True, verbose_name='Default username'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='default_password',
            field=models.CharField(blank=True, default='!Cisco@123', help_text='Default password used by AutoCli for SSH connections.', max_length=64, null=True, verbose_name='Default password'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='default_username',
            field=models.CharField(blank=True, default='cisco', help_text='Default username used by AutoCli for SSH connections.', max_length=64, null=True, verbose_name='Default username'),
        ),
    ]
