# Generated by Django 4.1 on 2022-08-09 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time of log occurrence.', verbose_name='Timestamp')),
                ('application', models.CharField(help_text='Name of the application which triggered the log.', max_length=64, verbose_name='Application')),
                ('correlated_object', models.CharField(help_text='Name of log related object.', max_length=64, null=True, verbose_name='Correlated object')),
                ('code_id', models.CharField(help_text='ID indicating the location of the log call in the code.', max_length=64, null=True, verbose_name='Code ID')),
                ('task_id', models.CharField(help_text='ID of the task associated with the log.', max_length=64, null=True, verbose_name='Task ID')),
                ('severity', models.IntegerField(choices=[(1, 'CRITICAL'), (2, 'ERROR'), (3, 'WARNING'), (4, 'INFO'), (5, 'DEBUG')], help_text='Log severity.', verbose_name='Severity')),
                ('message', models.CharField(help_text='Log message.', max_length=128, verbose_name='Message')),
                ('execution_time', models.FloatField(help_text='Log task completion time.', verbose_name='Execution time')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': ('Logs',),
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Extension name.', max_length=32, verbose_name='Name')),
                ('data', models.TextField(help_text='Extension data.', verbose_name='Data')),
                ('log', models.ForeignKey(help_text='Log corelate with log extension.', on_delete=django.db.models.deletion.CASCADE, to='logger.log', verbose_name='Log')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': ('Logs',),
            },
        ),
    ]
