# Generated by Django 4.1 on 2022-08-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extension',
            options={'verbose_name': 'Extension', 'verbose_name_plural': ('Extensions',)},
        ),
        migrations.RenameField(
            model_name='log',
            old_name='correlated_object',
            new_name='correlated',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='execution_time',
            new_name='execution',
        ),
    ]
