# Generated by Django 4.1 on 2022-08-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_alter_extension_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='code_id',
            field=models.CharField(blank=True, help_text='ID indicating the location of the log call in the code.', max_length=64, null=True, verbose_name='Code ID'),
        ),
        migrations.AlterField(
            model_name='log',
            name='correlated',
            field=models.CharField(blank=True, help_text='Name of log related object.', max_length=64, null=True, verbose_name='Correlated object'),
        ),
        migrations.AlterField(
            model_name='log',
            name='execution',
            field=models.FloatField(blank=True, help_text='Log task completion time.', null=True, verbose_name='Execution time'),
        ),
        migrations.AlterField(
            model_name='log',
            name='task_id',
            field=models.CharField(blank=True, help_text='ID of the task associated with the log.', max_length=64, null=True, verbose_name='Task ID'),
        ),
    ]
